services:
  - type: web
    name: aero-guardian
    env: python
    plan: free
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 1 --threads 1 --timeout 120
